apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  labels:
    app: {{ .Values.appName }}
data:
  POSTGRES_DB: {{ .Values.configmap.data.POSTGRES_DB }}
  POSTGRES_USER: {{ .Values.configmap.data.POSTGRES_USER }}
  POSTGRES_PASSWORD: {{ .Values.configmap.data.POSTGRES_PASSWORD }}