apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ .Values.appName }}-volume"
  labels:
    type: local
    app: {{ .Values.appName }}
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql2